# Generated by Django 4.1.4 on 2023-07-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custom_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_users',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
